/*https://framerusercontent.com/images/*/
export const projects = [
  {
    id: 1,
    title: 'Aire',
    description: 'Aire',
    image: '/images/kfr022WaJ8YJUyZFmdwCB3pXhs.jpg',
  },
  {
    id: 2,
    title: 'Correlated',
    description: 'Correlated',
    image: '/images/QVKFKT3dyGxloXfzzpurVKNMM6M.jpg',
  },
  {
    id: 3,
    title: 'Channel 5',
    description: 'Channel 5',
    image: '/images/AX9PukosNfGVcfXw3YapiYpl9g.jpg',
  },
  {
    id: 4,
    title: 'Ronald Abram',
    description: 'Ronald Abram',
    image: '/images/BAXywubxN8sAhfJg3AgGgFI.jpg',
  },
  {
    id: 5,
    title: 'Propeller',
    description: 'Propeller',
    video:
      '/videos/XuzMZ3Z1QQHKltPqRjzGnsWs27M~Jq48dGctHPeHtnn90xE_Aem-3HQJB_aNVwfu2fao5Ok.mp4',
  },
  {
    id: 6,
    title: 'Schuh',
    description: 'Schuh',
    image: '/images/3WALBX7nnuG7p85CLjlVmWPDHw.jpg',
  },
  {
    id: 7,
    title: 'Paperstreet',
    description: 'Paperstreet',
    image: '/images/e3moUZXfgtjYQY4ILakIMaz4n7s.jpg',
  },
  {
    id: 8,
    title: 'OH.SUPPLY',
    description: 'OH.SUPPLY',
    video:
      '/videos/SGjFvgcbK7s4yKh0xwuNjriMNII~5SCIlrVv6SNR5PFMjsMv3qAIi3sYsG2gjdlB0qM-tng.mp4',
  },
  {
    id: 9,
    title: 'Monokel Eyewear',
    description: 'Monokel Eyewear',
    image: '/images/aH1eUgCIIIrbJF7TUlaKAehoI.jpg',
  },
  {
    id: 10,
    title: 'Lawtrades',
    description: 'Lawtrades',
    image: '/images/UbS7rWmAwWxjtwM7oaWwRuGo.jpg',
  },
  {
    id: 11,
    title: 'Baselworld',
    description: 'Baselworld',
    image: '/images/hQVBeiDNGU2TfeDJALuhawlcto.jpg',
  },
  {
    id: 12,
    title: 'NYCB',
    description: 'NYCB',
    video:
      '/videos/NieGBlxBdgpz9QCHV5Aj89rWjVg~DPEeC0jYyBwx9c865cOkUi-KzBM-3ukyhpgtPhvYo_U.mp4',
  },
]

export const projectsDetail = {
  aire: {
    title: 'Aire',
    headline: 'A better way to deal with every day',
    description:
      'I worked with Aire to develop a brand that firmly positions them as a premium lifestyle brand. The name Aire was inspired by the companies conception in Aire Street Workshops, in addition to aligning well with how the product makes you feel. The wordmark has been designed to convey the feeling of ease and simplicity whilst encapsulating a premium feel. Aire believes in the power of CBD to help people manage the day to day a little better — so I developed a strap-line which embodied that message. A better way to deal with every day.',
    images: [
      '/images/mGxIaDhGjujbfshox24OyOTIc9E.jpg',
      '/images/KAXNtzMy2AYmtasCLdNEKIU2wI.jpg',
      '/images/yU8ZKQFThmUFqfC2FYZqcGbWw.jpg',
      '/images/1ZNxQVbQdraZjjmKyBwxrioAwvc.jpg',
      '/images/wQuOrcu37DXYfaXafEJ6y6Uo.jpg',
      '/images/kfr022WaJ8YJUyZFmdwCB3pXhs.jpg',
      '/images/DmSvG2vRgGHkjr2izJsUcpWPs.jpg',
      '/images/XyMJtcTk4JgOgG8gvE7Xo9ssy3E.gif',
      '/images/pRhnMswaeFkyMfJX0Hwwh0QTQ.jpg',
      '/images/3wAtzo0qvmxyJhsWXvruyTZtRU.jpg',
      '/images/XaVdbFmdnBjuIAO6uR2K4xlQ.jpg',
      '/images/i3WtVhahDcZd4OywmX9rXkq7yPo.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
    ],
  },
  correlated: {
    title: 'Correlated',
    headline: 'From onboarding to automation. A seamless user journey.',
    description:
      'I helped the Correlated team improve functionality across their platform and develop a series of new features, all backed up by a robust and distinct design system.',
    images: [
      '/images/QVKFKT3dyGxloXfzzpurVKNMM6M.jpg',
      '/images/68Iqel3D27Y4JufI8Uy5OvefWbc.jpg',
      '/images/1p2fh6pUhyWU5wo0HuUhGBfq0.jpg',
      '/images/vbrM0VmAH5DTwyk1LqtQmxL51s.jpg',
      '/images/tN8jTohPTXn5uQRpJxyX92NH4MI.jpg',
      '/images/eEacfQIEXZe97VYUR5elLz6s4.jpg',
      '/images/0nNRgAlDOtkHlL9Zy0g89qxnVBw.jpg',
      '/images/thOwwRtQEmgMsCmiIA6Pz32uHM.jpg',
      '/images/lFrqFqQHwbgjUIEdNoDqx0ByQbA.jpg',
      '/images/As3sZJW3p7ZozhuXUdkNipZNg.jpg',
      '/images/cWbxOdQuIb89b5L55hjKxdF7Jhw.jpg',
      '/images/7FjwLrD1PXJxWNaJnIs1otLhFI.jpg',
      '/images/QrI9yPy4AnRCf2rL3ZPEXaqeD2A.jpg',
      '/images/aiUDhsoiJ5PXdrBkmKQaCCyt8NE.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
    ],
  },
  channel5: {
    title: 'Channel 5',
    headline: 'A new interface for the My5 app',
    description: ' ',
    images: [
      '/images/AX9PukosNfGVcfXw3YapiYpl9g.jpg',
      '/images/jpsrtmn5ap2vvXaeFrEIH8inMSU.jpg',
      '/images/0KA0uiQb1NQkiRNqhWFBA94M6c.jpg',
      '/images/LSoDC8ZFPVuElz9MuIiCBy074.jpg',
      '/images/1bRUMuQGAUplFne04eTlsDVpfQo.jpg',
      '/images/lJE1pT1oMrucwvL3GnCeJh7KM.jpg',
      '/images/AOvySvXQ6r9DqoxddAF7AqkblUE.jpg',
      '/images/x7Tlx2PrrARHFwNS2AnmQ1tyeUM.jpg',
      '/images/hpIuUz2xC23ORVJQSwmbGjDk.jpg',
      '/images/Yntl0o6Eyr2t919TsaJoiLBF78.jpg',
      '/images/kesWJRzDkSLkSphTLLmr0NtmE.jpg',
      '/images/MEXS8GkZVeeiTZ3C2pmNw6k0.jpg',
      '/images/R1eCvxfLzWsDDDFfiCefJ2qOOI.jpg',
      '/images/7o4595twkcrtmzD2h79WFul53g.jpg',
    ],
    colspan: [
      'col-span-2',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
    ],
  },
  ronaldabram: {
    title: 'Ronald Abram',
    headline: 'A luxury jewellery brand rich in heritage',
    description: ' ',
    videos: [
      '/videos/Ibg2qaJfhWWgXfDgOI3At8X33Oo~OOe-ybKyyiB9Yof7q-luX4OTp_i5mJ4rC9Zm85u8Drw.mp4',
    ],
    images: [
      '/images/yoldrzeYkHYdQSQMr82toErhFuc.jpg',
      '/images/mM8gWL8EZhuRFFH9zKiCjeydL2M.jpg',
      '/images/PYK92ERzf6TBoL0o7RHEbUjl0.jpg',
      '/images/ClvUaGQRcQmltKtJs4rmnPkRIoY.gif',
      '/images/yUBwN4cGXcV7prUYFZkecjj0.jpg',
      '/images/MJ7bMMlAOq861TmG9oRLJde8U.jpg',
      '/images/acSEGCDjtyv11F6Tu4u13jg3U.jpg',
      '/images/ClvUaGQRcQmltKtJs4rmnPkRIoY.gif',
      '/images/PsFtrMsfil25WM1W3mnUe2okoI.jpg',
      '/images/r6iesplPUVaNWHGp9wkV51rK9Y.jpg',
      '/images/FseFmzFiyWaYDrJAXdokR2Dr0.jpg',
      '/images/ysuIdxwL4m7kIB9JVcHuKgYm8.jpg',
    ],
    colspan: [
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
      'col-span-2 sm:col-span-1',
      'col-span-2 sm:col-span-1',
      'col-span-2',
    ],
  },
}

export const experiences = [
  {
    id: 1,
    time: '2017 - Present',
    company: 'OH.STUDIO',
    title: 'Freelance Designer',
    tag: 'Director',
  },
  {
    id: 2,
    time: '2021 - Present',
    company: 'Friendly Studio',
    title: 'Lead Product Designer',
    tag: 'Freelance',
  },
  {
    id: 3,
    time: '2022',
    company: 'R/GA',
    title: 'Senior Visual Designer',
    tag: 'Freelance',
  },
  {
    id: 4,
    time: '2021',
    company: 'R/GA',
    title: 'Senior Visual Designer',
    tag: 'Freelance',
  },
  {
    id: 5,
    time: '2021',
    company: 'AKQA',
    title: 'Senior Designer',
    tag: 'Freelance',
  },
  {
    id: 6,
    time: '2020',
    company: 'AKQA',
    title: 'Senior Designer',
    tag: 'Freelance',
  },
  {
    id: 7,
    time: '2019',
    company: 'UI Centric',
    title: 'Senior Product Designer',
    tag: 'Freelance',
  },
  {
    id: 8,
    time: '2017',
    company: 'Agency TK',
    title: 'Senior Digital Designer',
    tag: 'Permanent',
  },
  {
    id: 9,
    time: '2012',
    company: 'Agency TK',
    title: 'Digital Designer',
    tag: 'Permanent',
  },
  {
    id: 10,
    time: '2009',
    company: 'Next Level',
    title: 'Digital Designer',
    tag: 'Permanent',
  },
  {
    id: 11,
    time: '2008',
    company: 'Next Level',
    title: 'Junior Digital Designer',
    tag: 'Permanent',
  },
]

export const clients = [
  {
    id: 1,
    name: 'Eurosport',
    image: '/images/nXLdc1LsU15dk6AODEpMgByLDw.png',
  },
  {
    id: 2,
    name: 'Rga',
    image: '/images/roAzNhDBr8shtI8EFOALn1BTMO0.png',
  },
  {
    id: 3,
    name: 'Nike',
    image: '/images/vzRTkTnoLuK5zvS2serU2qCb4.png',
  },
  {
    id: 4,
    name: 'Olympics',
    image: '/images/DFu6Bri5cuYIVyEC6OTxtuZC6w.png',
  },
  {
    id: 5,
    name: 'Schuh',
    image: '/images/IDRNrtKWyB6T6o3dY4mUDqueC0.png',
  },
  {
    id: 6,
    name: 'MuscleGun',
    image: '/images/X5Lg2eapOCFOhSpAFsZNTW9BlY.png',
  },
  {
    id: 7,
    name: 'AKQA',
    image: '/images/PCQIe7uLIcRFBG5bKFWCX3niBek.png',
  },
  {
    id: 8,
    name: 'World Gold Council',
    image: '/images/8w3YBn3xA3P0u5w43PGhPo1jpYA.png',
  },
  {
    id: 9,
    name: 'Five',
    image: '/images/LZKUjkgnsVfFzQQN8ia8Vsx05Gc.png',
  },
  {
    id: 10,
    name: 'Correlated',
    image: '/images/0SV0avmvDSqmXrnokG46LzlhDY.png',
  },
  {
    id: 11,
    name: 'Here',
    image: '/images/OcncVh5JYd0fPDgeMql6apXe7eU.png',
  },
  {
    id: 12,
    name: 'ZeroLight',
    image: '/images/370YdQkcdjKWJ5KnsDqECHExB3c.png',
  },
]

export const profiles = [
  {
    id: 1,
    name: 'profile 1',
    image: '/images/wJINOk3BFAbQRx6ZySXfbltPxU.jpg',
  },
  {
    id: 2,
    name: 'profile 2',
    image: '/images/O3Foxt0XkzTsjGc74Ap0Hrxtz4c.jpg',
  },
]
